FROM node:22-slim

RUN apt-get update && apt-get install -y curl python3 make g++ && rm -rf /var/lib/apt/lists/*

# Install dependencies
ADD [".", "/app/"]
WORKDIR /app
RUN npm ci

# Runtime Config
EXPOSE 3000
# CMD ["npm", "run", "start:debug"]
USER node
